### ISSUE TITLE
Audric's report

### ISSUE THREAD

**Issue by Bilb** [tomobre/optf-website#1]
Looking good!

Obviously didn't get to check it fully, but here are my comments: 

## General practice
- [x] using index for a key is bad practice in React. I don't think it matter for this website as everything is static but there are quite a few https://react.dev/learn/tutorial-tic-tac-toe#picking-a-key Search with `key={`
- [ ] There are a bunch of things which would be nice to not use JS but CSS for instance that `onMouseEnter={() => onHover(index, true)` but we won't fix it for now. Or this one: `{show ? ▼:►}`
- [ ] can we get rid of the only getServerSideProps and use static ones? If yes, we can probably also get rid of the `useMemo` as everything will be statically generated. I think we cannot as this is relevant for the preview of a blog post
- [ ] would be nice to get rid of the `: any` at some point, but no need to do it for now
- [x] there is a bunch of unused variables. Would be good to setup linting so you get warnings for those

# Pages

## contact us

- [x] the google recaptca on the contact us webpage is not working, but I suspect it's because the website is not deployed yet?
- [x] the submit button on the contact page has "Submit Button" as text :D

##  About optf
- [x] why is About optf and partners & allies black but the rest of the tabs in /about-opt text are grey? (and not very readable on text select)
[Screencast from 05-04-23 14:15:50.webm](https://user-images.githubusercontent.com/1544279/229979672-af349215-f4bc-4d00-8829-8f5c79d7ca7b.webm)
- [x] can you find svgs for the blurry icons down there about-optf / partners and allies ?

## Blog
- [x] the "If you’d like to contribute to our blog, get in touch with us here!" should probably be centered?
- [x] in http://localhost:3000/blog and http://localhost:3000/ it would be nice to have the click on the whole box rather than just the title of the blog post
- [x] the Read More in http://localhost:3000/blog boxes is not the same as in the one at the bottom of http://localhost:3000/blog/developers-have-already-started-analysing-covidsafe-call-on-government-to
![image](https://user-images.githubusercontent.com/1544279/229979435-c69b99f0-18c4-4208-9de6-646651abe1fc.png)
![image](https://user-images.githubusercontent.com/1544279/229979498-38370b7f-47be-4421-b48d-0505f29883f7.png)
- [ ] the box shadow on the blog article is a lot lighter in http://localhost:3000/ than in http://localhost:3000/blog

## Mobile Page: Research

- [x] on http://localhost:3000/research on mobile there is a big white space under the Download Report button 
![image](https://user-images.githubusercontent.com/1544279/229979333-0d42f896-dcf6-406c-847c-42276466ba2d.png)
- [x] on mobile, you can select multiple tabs like "Partners and Allies" and Funding at the same time
![image](https://user-images.githubusercontent.com/1544279/229979006-5ee3af30-5235-48ae-93d5-bc349e6715e1.png)
- [x] Might be related to the above multiple tabs issue: but on mobile on the hamburger menu you Have "Partner and Allies" and also the same entry as a tab in the tab http://localhost:3000/about-optf#2
![image](https://user-images.githubusercontent.com/1544279/229977917-a0f3d7b1-816b-44b7-b23e-5d0d9b20e5b6.png)
- [x] the privacy policies do not load with "Refused to display 'https://lokinet.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin"
![image](https://user-images.githubusercontent.com/1544279/229978003-6e4e6458-1b33-40d2-ae72-67fb7d1631af.png)
- [x] there is a media release item in the menu which does not link to anything (http://localhost:3000/media-releases)
![image](https://user-images.githubusercontent.com/1544279/229978365-43a2e8f8-c11c-4678-bc5d-712a4897881a.png)

# Components

## Footer
- [x] add hover effect matching the twitter and youtube ones in the bottom page
- [x] should the footer links to the same website open in a new tab?
-    Session Oxen and Lokinet makes sense
-    but for Contact Us, Get Involved, Donate now and Privacy Policy I'd expect them to open in the current tab rather than a new one.
- [x] footer (desktop), twitter icon is slightly too much on the left compared to the Social title
- [x] footer on mobile, the right Links are hardly readable (purple on dark purple) but on desktop they are while on dark purple
![image](https://user-images.githubusercontent.com/1544279/229979170-8b26e286-8cb0-4d64-a801-f7ac1eaf4e83.png)
- [x] your `  const renderFooter = () => {` is bad practice, get it out of the render function of Footer as another component in the same file 

## Header
- [x] I get this error while running it. Not sure if that would fix it: https://stackoverflow.com/a/66423250
![image](https://user-images.githubusercontent.com/1544279/229980325-a8b91213-3abd-42ec-95e8-c48b875a07d2.png)

## Banner
- [x] twice you do this: `!!` after a variable name. I am not too sure why you'd need to do it this way? Why not do the `!!image && ` instead of the `image!! &&`. From what I understand, the !! && disables typescript compile checks for null, but `!!image &&` just makes sure that image is set?

## BlogPost
- [x] `<>` is not needed here

## List
- [x] Not sure why you need dangerouslySetInnerHTML here. The only place you use <List is with a string. Why not just  `        return <li key={index} >{item}</li>;` here as there is nothing in those string requiring html?

## Pagination
- [x] why use any when not required to ? `paginationRange: any = usePagination` You can get rid of that any if you just do a `if(!paginationRange} return null` on the next line
- [x] there a two `<div />` in the app. I suppose you need them for css animations or whatever but just wanted to make sure

**Comment by KeeJef** [comment]
Just adding my feedback here
